apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: order
  labels:
    io.kompose.service: order-db-env
data:
      # MySQL
  DB_USERNAME: bmms_user
  DB_PASSWORD: bmms_password
  DB_ROOT_PASSWORD: root123

  # Payment Service DB config
  ORDER_SVC_DB_HOST: order-db
  ORDER_SVC_DB_PORT: "3306"
  ORDER_SVC_DB_USER: bmms_user
  ORDER_SVC_DB_PASS: bmms_password
  ORDER_SVC_DB_NAME: order_db

  # Kafka broker
  KAFKA_BROKER: redpanda-0.infras.svc.cluster.local:9092
  BILLING_SERVICE_URL: http://billing-service.billing.svc.cluster.local:3003
  PAYMENT_SERVICE_URL: http://payment-service.payment.svc.cluster.local:3015