apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  labels:
    app: order-svc
spec:
  replicas: 1           # chỉ định Kubernetes sẽ tạo 1 Pod hoặc nhiều pod để còn lại dự phòng
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:       # Chỉ định image base để chạy container kéo từ Docker Regỉstry
        - name: order-service
          image: 0xt4i/order-service:0.0.1
          ports:
            - containerPort: 3011
          envFrom:      # Nạp biến môi trường có tên env từ configmap và 
            - configMapRef:
                name: env
            - secretRef:
                name: mysql-secret
      restartPolicy: Always

