apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    app: order-db
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        app: order-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: order_db
            - name: MYSQL_PASSWORD
              value: bmms_password
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_USER
              value: bmms_user
          envFrom:
            - configMapRef:
                name: env
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - --password=root123
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          name: bmms-order-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: order-db-data
      restartPolicy: Always
      volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-data
