apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
  labels:
    io.kompose.service: order-service
spec:
  type: NodePort
  selector:
    io.kompose.service: order-service
  ports:
    - name: http
      port: 3011         # port trong cluster
      targetPort: 3011   # port trong container
      nodePort: 30011    # port ngo√†i node (30000-32767)
