apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - name: "3015"
      port: 3015
      targetPort: 3015
  selector:
    app: payment-service
